### ISSUE TITLE
`dist` folder is missing on npm with version 2.0.3

### ISSUE THREAD

**Issue by DanSnow** [syntax-tree/hast-util-from-dom#6]
### Subject of the issue

As you can see there is no `dist` folder https://unpkg.com/browse/hast-util-from-dom@2.0.3/

### Your environment

*   **OS**: 
*   **Packages**:  2.0.2 ~ 2.0.3
*   **Env**:

**Comment by wooorm** [comment]
Sorry about that, fixed in 2.0.4!

**Comment by DanSnow** [comment]
Thanks!
